[program:reverb]
command=php /home/u431417112/domains/scamfreeind.in/public_html/artisan reverb:start
autostart=true
autorestart=true
user=u431417112
redirect_stderr=true
stdout_logfile=/home/u431417112/domains/scamfreeind.in/public_html/storage/logs/reverb.log
stopasgroup=true
killasgroup=true
